SELECT A.CD_AGENDA, A.CD_PACIENTE, A.DT_AGENDA, P.DC_PACIENTE, P.DT_CRIADOEM FROM TB_AGENDA A  LEFT JOIN TB_PACIENTE P ON A.CD_PACIENTE = P.CD_PACIENTE ORDER BY CD_AGENDA ASC

UPDATE TB_AGENDA SET DT_AGENDA = '2020-13-03 00:00:00', CD_PACIENTE=NULL WHERE CD_AGENDA = 4

SELECT * FROM TB_PACIENTE ORDER BY CD_PACIENTE ASC

SELECT * FROM TB_PACIENTE WHERE CD_PACIENTE = 1

DELETE FROM TB_PACIENTE WHERE CD_PACIENTE = 1

UPDATE TB_PACIENTE SET DC_PACIENTE = 'Biscoito dos Santos Piran Campos' WHERE CD_PACIENTE = 1

INSERT INTO TB_PACIENTE (DC_PACIENTE) VALUES ('Biscoito Piran Campos') 
GO

INSERT INTO TB_PACIENTE (DC_PACIENTE) VALUES ('Henri Piran Campos') 
GO

INSERT INTO TB_PACIENTE (DC_PACIENTE) VALUES ('Janaina Campos') 
GO

INSERT INTO TB_PACIENTE (DC_PACIENTE) VALUES ('Renata Piran Campos') 
GO

INSERT INTO TB_PACIENTE (DC_PACIENTE) VALUES ('Alexander Campos') 
GO

create database db_ness_entrevista